version: "3.3"
services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes: 
      - mysql_data:/var/lib/mysql
    env_file: 
      - ./.env
  vanilla-forums: 
    image: vanillaforums
    build:
      context:  ./src
    container_name: vanilla-forums
    restart: always
    volumes:
      - uploads:/var/www/html/upload
    ports:
      - 80:80
volumes:
  mysql_data:
  uploads: